---
version: "3"

volumes:
  photosobliques_data:

services:

  photosobliques:
    image: photos-obliques-image
    ports:
      - "{{photosobliques_server_expose_port}}:{{photosobliques_server_port}}"      
    volumes:
      - ./config:/etc/georchestra
      - ./photosobliques_data:/opt/photosobliques/data
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - ADD_JAVA_OPTS=
      - XMX=1G

