proxy:
  build: proxy
  ports:
    - "8080:8080"
  links:
    - mapfishapp
    - pluievolution
    - header
  environment:
    - XMX=512M

pluievolution:
  build: pluievolution
  environment:
    - ADD_JAVA_OPTS=-Dgeorchestra.datadir=/etc/georchestra

header:
  environment:
    - XMX=512M
  image: georchestra/header
