proxy:
  build: proxy
  ports:
    - "8080:8080"
  links:
    - photosobliques
    - header
  environment:
    - XMX=512M

photosobliques:
  build: photosobliques
  environment:
    - ADD_JAVA_OPTS=-Dgeorchestra.datadir=/etc/georchestra

header:
  environment:
    - XMX=512M
  image: georchestra/header
